### PR TITLE
#150 Group the tests by features, refactor tailor instance creation i…

### LINKED ISSUE #150: do something to make the tests look better
https://github.com/zalando/tailor/blob/master/tests/tailor.js - this file has been growing with every new feature and its kind of hard to go through the test case if one fails. We can do few things here

- Reduce the test cases and keep it simple
- Lots of repetition across the code, need to fix - Write a small helper

### PR DESCRIPTION
**Pull request by addityasingh**
- closes #150 
- [x] Group the tests by features, 
- [x] Refactor tailor instance creation into function
- [x] Remove duplicates. (Use `jscpd -f "tests/*.js" -e "**/node_modules/**"` to find and remove 
duplicates)

### CODE REVIEW

File: tests/tailor.js [hunk 1]
```diff
@@ -449,356 +424,396 @@ describe('Tailor', () => {
...
+            }).then(done, done);
+        });
     });
 
-    it('shouldn\'t send preloading headers if primary fragment doesn\'t exist', (done) => {
-        nock('https://fragment')
-            .get('/1').reply(200, 'hello', {
-                'Link': '<http://link>; rel="stylesheet",<http://link>; rel="fragment-script"'
-            });
+    describe('Headers::Tailor', () => {
```
Comment (vigneshshanmugam) [inline tests/tailor.js]: Already exists before.

**Comment by vigneshshanmugam** [comment]
Awesome work :) Thanks a lot
